config/routes.rb
Rails.application.routes.draw do




  namespace :admin do
    resources :point_infos
  end
  namespace :admin do
  resources :user_gift_requests do
     member do
     get "gift_request_send"
     end
  end
  end
  namespace :admin do
    resources :offers
  end
	root "common#index"


# resources :albums do
# 	member do
# 		get 'album_songs'
# 	end
# end
    resources :subscribe_news do
    collection do
    	post 'subscribe_me' => "subscribe_news#subscribe_me"
    end
   end
    resources :notifications do
    	collection do
         get 'unread_notification' => "notifications#unread_notification"
         get 'notification_list' => "notifications#notification_list"
         post 'update_notification' => "notifications#update_notification"

       end
   end
	resources :albums do
     member do
      	get 'album_songs' => "albums#republic"
      end
      collection do
	   get 'add_album' => "albums#add_album"
	   post 'create_album' => "albums#create"
	   get 'albums' => "albums#index"
	   

     end
   end
   resources :genres , except: [:show]  do
   	collection do
   	get 'upload_song' => "genres#upload_song"
   end
   end
    resources :songs 
     post 'add_song'=>"songs#create"

    resources :user
	get 'profile' => "users#profile"
	put "update_password" => "users#update_password"
    
	get 'usersetting' => "users#usersetting"
	get 'my_profile' => "users#my_profile"
	patch 'update_profile' => "users#update_profile"
	get 'notifications' => "notifications#notifications"
	get 'setting' => "notifications#setting"
  
	get 'forgetpassword' => "common#forgetpassword"
     post "social_login" => "common#social_login"
	get 'contact_us' => "common#contact_us"
	get 'about_us' => "common#about_us"
	get 'privacy' => "common#privacy"
	get 'how_it_work' => "common#how_it_work"
	

	get  "common/check_email"
 



  namespace :admin do
    resources :genres
  end
  namespace :admin do
    resources :users
    
    get "/" => "users#dashboard"
    
    get "/change_password" => "users#change_password"
    get "/update_password" => "users#update_password"
    get  "/check_email"   => "users#check_email"
 
    
  end

   get "set_password" => "common#set_password"
   put "updatepassword" => "common#update_password"
   
  
# devise_for :users, controllers: {
#   sessions: 'users/sessions'
# }

   devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

	namespace :api, defaults: { format: :json } do
		namespace :v1 do
			resources :users, only: [:index] do
				collection do
				  get "me"
				  post "sign_in"
				  get "sign_out"
				  post "sign_up"
				  post "update"
				  get "recent_music"
				  get "followings"
				  get "followers"
				  post "review"
				  get "reviews"
				  post "select_genre"
				  get "common_genre"
				  post "forgot_password"
				  post "varify_otp" 
				  post "varify_forgot_otp" 
				  post "update_password" 
				  post "change_current_password" 
				  get "get_points"
				  get "get_offers"
				   post "resend_otp"
				   post "browse"
				   post "social_login"
				   post "setting_notification"
				   get "all_notification"
				   get "unread_notification"
				   
				end
				member do
				  get "profile"
				  get "add_new_point"
                 end
				  get "follow"
				  get "unfollow"
				  get "remove_from_favorite"
				  get "add_to_favourite"
			end
			resources :user_playlists do
				get "playlist_songs"
				post "add_song"
				get  "delete"

			end
			 resources :offers do
			    	 member do
			      	get 'redeem_offer' => "offer#redeem_offer"
			      end
              end
			resources :genres, only: [:index] do
				resources :albums, only:[:index,:show]
				collection do
				  get "all"
				 end
			end
			 
			
			
            resources :songs, only: [:play] do
                member do
				  get "play"
				  get "full_play"
				  
                end
				 collection do
				 	 get "recent_play_list"
				 	 get "all_songs"
				 	 
				 end
				  post "review"
				  get "reviews"
				  get "remove_from_favorite"
				  get "add_to_favourite"
            end
		end
	end

end

app/models/user_gift_request.rb
class UserGiftRequest < ApplicationRecord
  belongs_to :user
  belongs_to :offer
end

app/controllers/admin/user_gift_requests_controller.rb
class Admin::UserGiftRequestsController < ApplicationController
  before_action :set_user_gift_request, only: [:show, :edit, :update, :destroy]
layout 'admin'
  # GET /admin/user_gift_requests
  # GET /admin/user_gift_requests.json
  def index
    @user_gift_requests = UserGiftRequest.all
  end
  def gift_request_send
    begin
    @gift =  UserGiftRequest.find(params[:id])
    @offer =  Offer.find(@gift.offer_id)
    @user =  User.find(@gift.user_id)
    userpoints  = @user.total_points-@offer.points
    @user.update(:total_points=>userpoints)
    
     @gift.update(:status=>true)
    if  @user.gift_notification==true
      reciever = @user
      hsh = {}
        hsh = HashWithIndifferentAccess.new
        hsh[:title] = "Gift Card"
        hsh[:message] = "Your  points turned into Gift Card now!"
        hsh[:notification_type] = "gift_card"
        hsh[:notification_type_id] = @user.id
        @user.send_notification_by_admin(hsh,reciever)
      end
     flash[:success] = "Gift card sent successfully!"
    redirect_to admin_user_gift_requests_path
   rescue Exception => e
      err_hash = HashWithIndifferentAccess.new
      err_hash[:error] = e.message
      status = :bad_request
      render :json => err_hash.to_json, status: status
   end
  end
  # GET /admin/user_gift_requests/1
  # GET /admin/user_gift_requests/1.json
  def show
  end

  # GET /admin/user_gift_requests/new
  def new
    @user_gift_request = UserGiftRequest.new
  end

  # GET /admin/user_gift_requests/1/edit
  def edit
  end

  # POST /admin/user_gift_requests
  # POST /admin/user_gift_requests.json
  def create
    @user_gift_request = UserGiftRequest.new(user_gift_request_params)

    respond_to do |format|
      if @user_gift_request.save
        format.html { redirect_to admin_user_gift_requests_path, notice: 'User gift request was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user_gift_request }
      else
        format.html { render action: 'new' }
        format.json { render json: @user_gift_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/user_gift_requests/1
  # PATCH/PUT /admin/user_gift_requests/1.json
  def update
    respond_to do |format|
      if @user_gift_request.update(user_gift_request_params)
        format.html { redirect_to admin_user_gift_requests_path, notice: 'User gift request was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user_gift_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/user_gift_requests/1
  # DELETE /admin/user_gift_requests/1.json
  def destroy
    @user_gift_request.destroy
    respond_to do |format|
      format.html { redirect_to admin_user_gift_requests_url, notice: 'User gift request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_gift_request
      @user_gift_request = UserGiftRequest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_gift_request_params
      params.require(:user_gift_request).permit(:id, :user_id, :offer_id, :created_at, :status)
    end
end

app/helpers/admin/user_gift_requests_helper.rb
module Admin::UserGiftRequestsHelper
end

app/views/admin/user_gift_requests/_form.html.erb
<%= form_for([:admin, @user_gift_request], html: { class: 'form-horizontal user_gift_request' }) do |f| %>
  <% if @user_gift_request.errors.any? %>
    <div id="error_explanation" class="panel panel-danger">
      <div class="panel-heading">
        <h2 class="panel-title"><%= pluralize(@user_gift_request.errors.count, "error") %> prohibited this user_gift_request from being saved:</h2>
      </div>
      <div class="panel-body">
        <ul>
        <% @user_gift_request.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :id, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.number_field :id, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :user_id, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.number_field :user_id, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :offer_id, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.number_field :offer_id, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :created_at, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.datetime_select :created_at, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-md-offset-2 col-md-10">
      <%= f.label :status, for: nil do %>
        <%= f.check_box :status %>
        <%= UserGiftRequest.human_attribute_name(:status) %>
      <% end %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-md-offset-2 col-md-10">
      <%= f.submit nil, class: 'btn btn-primary' %>
      <%= link_to 'Back', admin_user_gift_requests_path, class: 'btn btn-default',style:"margin-top: 11px;
        margin-left: 20px;" %>
    </div>
  </div>
<% end %>

app/views/admin/user_gift_requests/edit.html.erb
<div class="page-header">
  <h1>Editing user_gift_request</h1>
</div>

<%= render 'form' %>

<%#= link_to 'Show', [:admin, @user_gift_request], class: 'btn btn-default' %>
<%#= link_to 'Back', admin_user_gift_requests_path, class: 'btn btn-default' %>

app/views/admin/user_gift_requests/index.html.erb
<div class="page-header">
  <h1>Listing Gift Card Requests</h1>
</div>

<% if @user_gift_requests.present? %>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Id</th>
      <th>User</th>
      <th>UserEmail</th>
      <th>Requested Prize</th>
      <th>Points Redeem</th>
 
      <th>Created at</th>
      <th>Status</th>
      <th>Action</th>
      
    </tr>
  </thead>

  <tbody>
    <% @user_gift_requests.each do |user_gift_request| %>
      <tr>
        <td><%= user_gift_request.id %></td>
        <td><%= User.find(user_gift_request.user_id).first_name %></td>
        <td><%= User.find(user_gift_request.user_id).email %></td>
        <td><%= Offer.find(user_gift_request.offer_id).offer_prize %></td>
        <td><%= Offer.find(user_gift_request.offer_id).points %></td>
        <td><%= user_gift_request.created_at %></td>
        <td><% if(user_gift_request.status==true) %><%= link_to 'Gift Card sent',"#", class: 'btn btn-success btn-xs' %><%else%><%= link_to 'Gift Card send', gift_request_send_admin_user_gift_request_path(user_gift_request.id), class: 'btn btn-default btn-xs' %><%end%></td> <td><%= link_to 'Show', [:admin, user_gift_request], class: 'btn btn-default btn-xs' %>
       <%= link_to 'Edit', edit_admin_user_gift_request_path(user_gift_request), class: 'btn btn-default btn-xs' %><%= link_to 'Destroy', [:admin, user_gift_request], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-xs btn-danger',:style=>"margin-left:5px;" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
No Request available
<% end %>

<br>

<%#= link_to 'New User gift request', new_admin_user_gift_request_path, class: 'btn btn-primary' %>

app/views/admin/user_gift_requests/new.html.erb
<div class="page-header">
  <h1>New user_gift_request</h1>
</div>

<%= render 'form' %>

<%= link_to 'Back', admin_user_gift_requests_path, class: 'btn btn-default' %>

app/views/admin/user_gift_requests/show.html.erb
<p id="notice"><%= notice %></p>
 <div class="main-container" style="margin-top: 100px;">
<dl class="dl-horizontal">
  <dt><strong>Id:</strong></dt>
  <dd><%= @user_gift_request.id %></dd>
</dl>

<dl class="dl-horizontal">
  <dt><strong>User:</strong></dt>
  <dd><%= @user_gift_request.user_id %></dd>
</dl>

<dl class="dl-horizontal">
  <dt><strong>Offer:</strong></dt>
  <dd><%= @user_gift_request.offer_id %></dd>
</dl>

<dl class="dl-horizontal">
  <dt><strong>Created at:</strong></dt>
  <dd><%= @user_gift_request.created_at %></dd>
</dl>



<%= link_to 'Edit', edit_admin_user_gift_request_path(@user_gift_request), class: 'btn btn-default' %>
<%= link_to 'Back', admin_user_gift_requests_path, class: 'btn btn-default' %>
</div>