config/routes.rb
Rails.application.routes.draw do




  namespace :admin do
    resources :point_infos
  end
  namespace :admin do
  resources :user_gift_requests do
     member do
     get "gift_request_send"
     end
  end
  end
  namespace :admin do
    resources :offers
  end
	root "common#index"


# resources :albums do
# 	member do
# 		get 'album_songs'
# 	end
# end
    resources :subscribe_news do
    collection do
    	post 'subscribe_me' => "subscribe_news#subscribe_me"
    end
   end
    resources :notifications do
    	collection do
         get 'unread_notification' => "notifications#unread_notification"
         get 'notification_list' => "notifications#notification_list"
         post 'update_notification' => "notifications#update_notification"

       end
   end
	resources :albums do
     member do
      	get 'album_songs' => "albums#republic"
      end
      collection do
	   get 'add_album' => "albums#add_album"
	   post 'create_album' => "albums#create"
	   get 'albums' => "albums#index"
	   

     end
   end
   resources :genres , except: [:show]  do
   	collection do
   	get 'upload_song' => "genres#upload_song"
   end
   end
    resources :songs 
     post 'add_song'=>"songs#create"

    resources :user
	get 'profile' => "users#profile"
	put "update_password" => "users#update_password"
    
	get 'usersetting' => "users#usersetting"
	get 'my_profile' => "users#my_profile"
	patch 'update_profile' => "users#update_profile"
	get 'notifications' => "notifications#notifications"
	get 'setting' => "notifications#setting"
  
	get 'forgetpassword' => "common#forgetpassword"
     post "social_login" => "common#social_login"
	get 'contact_us' => "common#contact_us"
	get 'about_us' => "common#about_us"
	get 'privacy' => "common#privacy"
	get 'how_it_work' => "common#how_it_work"
	

	get  "common/check_email"
 



  namespace :admin do
    resources :genres
  end
  namespace :admin do
    resources :users
    
    get "/" => "users#dashboard"
    
    get "/change_password" => "users#change_password"
    get "/update_password" => "users#update_password"
    get  "/check_email"   => "users#check_email"
 
    
  end

   get "set_password" => "common#set_password"
   put "updatepassword" => "common#update_password"
   
  
# devise_for :users, controllers: {
#   sessions: 'users/sessions'
# }

   devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

	namespace :api, defaults: { format: :json } do
		namespace :v1 do
			resources :users, only: [:index] do
				collection do
				  get "me"
				  post "sign_in"
				  get "sign_out"
				  post "sign_up"
				  post "update"
				  get "recent_music"
				  get "followings"
				  get "followers"
				  post "review"
				  get "reviews"
				  post "select_genre"
				  get "common_genre"
				  post "forgot_password"
				  post "varify_otp" 
				  post "varify_forgot_otp" 
				  post "update_password" 
				  post "change_current_password" 
				  get "get_points"
				  get "get_offers"
				   post "resend_otp"
				   post "browse"
				   post "social_login"
				   post "setting_notification"
				   get "all_notification"
				   get "unread_notification"
				   
				end
				member do
				  get "profile"
				  get "add_new_point"
                 end
				  get "follow"
				  get "unfollow"
				  get "remove_from_favorite"
				  get "add_to_favourite"
			end
			resources :user_playlists do
				get "playlist_songs"
				post "add_song"
				get  "delete"

			end
			 resources :offers do
			    	 member do
			      	get 'redeem_offer' => "offer#redeem_offer"
			      end
              end
			resources :genres, only: [:index] do
				resources :albums, only:[:index,:show]
				collection do
				  get "all"
				 end
			end
			 
			
			
            resources :songs, only: [:play] do
                member do
				  get "play"
				  get "full_play"
				  
                end
				 collection do
				 	 get "recent_play_list"
				 	 get "all_songs"
				 	 
				 end
				  post "review"
				  get "reviews"
				  get "remove_from_favorite"
				  get "add_to_favourite"
            end
		end
	end

end

app/models/genre.rb
class Genre < ApplicationRecord
	has_many :albums,dependent: :destroy
	has_many :songs,through: :albums
	has_many :user_genres,dependent: :destroy
	has_many :users, through: :albums,dependent: :destroy
	mount_uploader :image, GenreUploader
	mount_base64_uploader :image, GenreUploader
	mount_uploader :icon_image, GenreUploader
	mount_base64_uploader :icon_image, GenreUploader

	 def current_uploaded_songs
	 	songs.where(:is_submit => 1)
	 end

	 def remove_uploaded_songs
	 	 current_uploaded_songs.map(&:destroy)
	 	# current_uploaded_songs.update_all(:is_submit => 2)
	 end

	 def songs_available_to_upload
	 	songs.where(:is_submit => 0)
	 end

	 def upload_songs_and_remove_old_songs
	 	remove_uploaded_songs
	 	first_thousand_songs_for_upload.update_all(:is_submit => 1)
	 	remaing_upload if current_uploaded_songs.count < 1000
	 end

	 def max_songs_to_upload
	 	return 1000
	 end

	 def remaing_upload
	 	remaining_song_to_upload = 1000 - current_uploaded_songs.count
	 	remaining_album_ids = albums.map(&:id) - current_uploaded_songs.map(&:album_id)
	 	next_album = Album.where(:id => remaining_album_ids).joins(:songs).order("songs.id asc").first
	 	if next_album.present?
	 	next_album.songs.where(:is_submit => 0).order("id asc").limit(remaining_song_to_upload).update_all(:is_submit => 1)
	    end
	 end
     def self.upload_all_genre_song

      # all.each {|gr| gr.upload_songs_and_remove_old_songs}
      self.delay(queue: "Job", priority: 5, run_at: 7.days.from_now).upload_all_genre_song
     
     end
	 def first_thousand_songs_for_upload
	 	# puts "songs_available_to_upload"
	 	# puts songs_available_to_upload
	 	# puts "max_songs_to_upload"
	 	# puts max_songs_to_upload
	 	if songs_available_to_upload.count > max_songs_to_upload
	 		album_ids = songs.map(&:album_id).uniq
	 		albums = Album.where(:id => album_ids)
		 	# puts "album_ids"
		 	# puts album_ids
	 		upload_albums_array = []
	 		song_count = 0
	 		albums.joins(:songs).order("songs.id asc").uniq.each do |album|
		 	# puts "album"
		 	# puts album.id
	 			if song_count < max_songs_to_upload
		 	# puts "song_count"
		 	# puts song_count
		 	# puts "max_songs_to_upload"
		 	# puts max_songs_to_upload
	 				current_song_count = album.songs.count
	 				if current_song_count < (max_songs_to_upload - song_count)
		 				song_count = song_count + current_song_count
		 				upload_albums_array.push album.id
		 			end
	 			else
	 				break
	 			end
	 		end
		 	puts "upload_albums_array"
		 	puts upload_albums_array
	 			songs = Song.where(:album_id => upload_albums_array) 
		 	puts "songs"
		 	# puts songs
	 			return songs
	 	else
		 	puts "else"
		 	# puts songs_available_to_upload
	 		return songs_available_to_upload
	 	end
	 end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :set_genre, only: [:show, :edit, :update, :destroy]
layout 'admin'
  # GET /admin/genres
  # GET /admin/genres.json
  def index
    @genres = Genre.all.paginate(:page => params[:page])
  end

  # GET /admin/genres/1
  # GET /admin/genres/1.json
  def show
  end

  # GET /admin/genres/new
  def new
    @genre = Genre.new
  end

  # GET /admin/genres/1/edit
  def edit
  end

  # POST /admin/genres
  # POST /admin/genres.json
  def create
    @genre = Genre.new(genre_params)

    respond_to do |format|
      if @genre.save
        format.html { redirect_to admin_genres_path, notice: 'Genre was successfully created.' }
        format.json { render action: 'show', status: :created, location: @genre }
      else
        format.html { render action: 'new' }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/genres/1
  # PATCH/PUT /admin/genres/1.json
  def update
    respond_to do |format|
      if @genre.update(genre_params)
        format.html { redirect_to admin_genres_path, notice: 'Genre was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/genres/1
  # DELETE /admin/genres/1.json
  def destroy
    @genre.destroy
    respond_to do |format|
      format.html { redirect_to admin_genres_path, notice: 'Genre was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_genre
      @genre = Genre.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def genre_params
      params.require(:genre).permit(:name, :image,:icon_image, :status)
    end
end

app/controllers/api/v1/genres_controller.rb
class Api::V1::GenresController < Api::V1::ApplicationController
	def index
			
			begin
				     @genre = Genre.paginate(:page => params[:page], :per_page => 6)
					 render :show_genre
				
		 	rescue Exception => e
		 		puts "error_exception #{Time.now} #{e.message}"
				err_hash={}
				err_hash[:error]=e.message
				render :json => err_hash.to_json  , status: :bad_request 
		 	end
		end

        def album
			
			begin
		album_ids =Album.joins(:songs).where('songs.is_submit'=>1).where("albums.genre_id"=>params[:genre_id]).map(&:id).uniq
		@album = Album.where(:genre_id=>params[:genre_id]).where(:id=>album_ids).order("id desc")
					 render :show_album
				
		 	rescue Exception => e
		 		puts "error_exception #{Time.now} #{e.message}"
				err_hash={}
				err_hash[:error]=e.message
				render :json => err_hash.to_json  , status: :bad_request 
		 	end
		end
end

app/controllers/genre_controller.rb
class GenresController < ApplicationController
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
	 def upload_song
      g = Genre.all
     g.each do |gr|
          gr.upload_songs_and_remove_old_songs
     end
  end
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/genre_helper.rb
module GenreHelper
end

app/views/admin/genres/_form.html.erb
<%= form_for([:admin, @genre], html: { class: 'form-horizontal genre' }) do |f| %>
  <% if @genre.errors.any? %>
    <div id="error_explanation" class="panel panel-danger">
      <div class="panel-heading">
        <h2 class="panel-title"><%= pluralize(@genre.errors.count, "error") %> prohibited this genre from being saved:</h2>
      </div>
      <div class="panel-body">
        <ul>
        <% @genre.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :name,:required => true, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :image,:required => true, class: 'control-label col-md-2' %>
    <div class="col-md-10">
    <%# debugger %>
    <% if @genre.id.nil? %>
      <%= f.file_field :image,:required => true,accept: "image/*" %>
      <%else%>
       <%= f.file_field :image,accept: "image/*" %>
       <img id="blah" src="<%=@genre.image%>" class= "form-control img-thumbnail" />
      <%end%>
    </div>
  </div>
   <div class="form-group">
    <%= f.label :icon_image, class: 'control-label col-md-2' %>
    <div class="col-md-10">
    <% if @genre.id.nil? %>
      <%= f.file_field :icon_image,:required => true,accept: "image/*" %>
      <%else%>
       <%= f.file_field :icon_image,accept: "image/*" %>
        <img id="blah" src="<%=@genre.icon_image%>" class= "form-control img-thumbnail" />
      <%end%>
    </div>
  </div>
  <!-- <div class="form-group">
    <div class="col-md-offset-2 col-md-10">
      <%#= f.label :status, for: nil do %>
        <%#= f.check_box :status %>
        <%#= Genre.human_attribute_name(:status) %>
      <%# end %>
    </div>
  </div> -->
  <div class="form-group">
    <div class="col-md-offset-2 col-md-10">
      <%= f.submit nil, class: 'btn btn-primary' %>
      <% if(@genre.name!='') %>
     <%= link_to 'Show', [:admin, @genre], class: 'btn btn-default',style:"margin-top: 11px;
        margin-left: 20px;" %>
        <% end %>
     <%= link_to 'Back', admin_genres_path, class: 'btn btn-default',style:"margin-top: 11px;
        margin-left: 20px;" %>
        
    </div>
  </div>
<% end %>
<script type="text/javascript">
  $("#new_genre").validate({
    messages:{
    "genre[image]": {
                    accept: "Please select an image file"
                },
    "genre[icon_image]": {
                    accept: "Please select an image file"
                },
          }
                
  })

</script>

app/views/admin/genres/edit.html.erb
<div class="page-header">
  <h1>Editing genre</h1>
</div>

<%= render 'form' %>

app/views/admin/genres/index.html.erb
<div class="page-header">
  <h1>Listing genres</h1>

</div>
  <%= link_to 'New Genre', new_admin_genre_path, class: 'btn btn-primary', style: "float:right;" %>

<table class="table table-responsive table-hover table-bordered  table-condensed">
  <thead>
    <tr>
      <th>#</th>
      <th>Name</th>
      <th>Image</th>
     
      <th></th>
      
    </tr>
  </thead>

  <tbody>
    <% @genres.each do |genre| %>
      <tr>
        <td><%= genre.id %></td>
        <td><%= genre.name %></td>
         <td><%=image_tag genre.image ,alt: '',size: "46x46",style: "margin-top: 7px;"%></td>
          <td><%= link_to 'View', [:admin, genre], class: 'btn btn-default btn-xs' %><%= link_to 'Edit', edit_admin_genre_path(genre), class: 'btn btn-default btn-xs',style: "margin-left: 7px;" %>
<%= link_to 'Destroy', [:admin, genre], method: :delete, data: { confirm: 'Are you sure? If yes then all albums and  songs will be deleted blongs to this genre ' }, class: 'btn btn-xs btn-danger',style: "margin-left: 7px;" %>
<%#= link_to 'Destroy', [:admin, genre], method: :delete, data: { confirm: 'Are you sure?' },style: "margin-left: 7px;" ,class: 'btn btn-xs btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if @genres.blank?%>
<i><span style="font-size: 25px; margin-left: 38%;">No Genre Found</span></i>
<%end%>
<div class="digg_pagination">
   
    <%= will_paginate @genres, :container => false %>
  </div>

app/views/admin/genres/new.html.erb
<div class="page-header">
  <h1>New genre</h1>
</div>

<%= render 'form' %>

<%#= link_to 'Back', admin_genres_path, class: 'btn btn-default' %>

app/views/admin/genres/show.html.erb
<p id="notice"><%#= notice %></p>
 <div class="main-container" style="margin-top: 100px;">
<dl class="dl-horizontal">
  <dt><strong>Name:</strong></dt>
  <dd><%= @genre.name %></dd>
</dl>

<dl class="dl-horizontal">
  <dt><strong>Image:</strong></dt>

  <dd> <%if @genre.image.present?%>
         <%=image_tag @genre.image ,alt: '',class: "img-rounded img-responsive",:size => "100x200" %>
         <%else%>
         <%= image_tag "default_user.png",class: "img-img-rounded img-responsive",:size => "380x500"%>
         <%end%></dd>
</dl>

<!-- <dl class="dl-horizontal">
  <dt><strong>Status:</strong></dt>
  <dd><%= @genre.status %></dd>
</dl> -->

<%= link_to 'Edit', edit_admin_genre_path(@genre), class: 'btn btn-default' %>
<%= link_to 'Back', admin_genres_path, class: 'btn btn-default' %>
</div>