config/routes.rb
Rails.application.routes.draw do




  namespace :admin do
    resources :point_infos
  end
  namespace :admin do
  resources :user_gift_requests do
     member do
     get "gift_request_send"
     end
  end
  end
  namespace :admin do
    resources :offers
  end
	root "common#index"


# resources :albums do
# 	member do
# 		get 'album_songs'
# 	end
# end
    resources :subscribe_news do
    collection do
    	post 'subscribe_me' => "subscribe_news#subscribe_me"
    end
   end
    resources :notifications do
    	collection do
         get 'unread_notification' => "notifications#unread_notification"
         get 'notification_list' => "notifications#notification_list"
         post 'update_notification' => "notifications#update_notification"

       end
   end
	resources :albums do
     member do
      	get 'album_songs' => "albums#republic"
      end
      collection do
	   get 'add_album' => "albums#add_album"
	   post 'create_album' => "albums#create"
	   get 'albums' => "albums#index"
	   

     end
   end
   resources :genres , except: [:show]  do
   	collection do
   	get 'upload_song' => "genres#upload_song"
   end
   end
    resources :songs 
     post 'add_song'=>"songs#create"

    resources :user
	get 'profile' => "users#profile"
	put "update_password" => "users#update_password"
    
	get 'usersetting' => "users#usersetting"
	get 'my_profile' => "users#my_profile"
	patch 'update_profile' => "users#update_profile"
	get 'notifications' => "notifications#notifications"
	get 'setting' => "notifications#setting"
  
	get 'forgetpassword' => "common#forgetpassword"
     post "social_login" => "common#social_login"
	get 'contact_us' => "common#contact_us"
	get 'about_us' => "common#about_us"
	get 'privacy' => "common#privacy"
	get 'how_it_work' => "common#how_it_work"
	

	get  "common/check_email"
 



  namespace :admin do
    resources :genres
  end
  namespace :admin do
    resources :users
    
    get "/" => "users#dashboard"
    
    get "/change_password" => "users#change_password"
    get "/update_password" => "users#update_password"
    get  "/check_email"   => "users#check_email"
 
    
  end

   get "set_password" => "common#set_password"
   put "updatepassword" => "common#update_password"
   
  
# devise_for :users, controllers: {
#   sessions: 'users/sessions'
# }

   devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

	namespace :api, defaults: { format: :json } do
		namespace :v1 do
			resources :users, only: [:index] do
				collection do
				  get "me"
				  post "sign_in"
				  get "sign_out"
				  post "sign_up"
				  post "update"
				  get "recent_music"
				  get "followings"
				  get "followers"
				  post "review"
				  get "reviews"
				  post "select_genre"
				  get "common_genre"
				  post "forgot_password"
				  post "varify_otp" 
				  post "varify_forgot_otp" 
				  post "update_password" 
				  post "change_current_password" 
				  get "get_points"
				  get "get_offers"
				   post "resend_otp"
				   post "browse"
				   post "social_login"
				   post "setting_notification"
				   get "all_notification"
				   get "unread_notification"
				   
				end
				member do
				  get "profile"
				  get "add_new_point"
                 end
				  get "follow"
				  get "unfollow"
				  get "remove_from_favorite"
				  get "add_to_favourite"
			end
			resources :user_playlists do
				get "playlist_songs"
				post "add_song"
				get  "delete"

			end
			 resources :offers do
			    	 member do
			      	get 'redeem_offer' => "offer#redeem_offer"
			      end
              end
			resources :genres, only: [:index] do
				resources :albums, only:[:index,:show]
				collection do
				  get "all"
				 end
			end
			 
			
			
            resources :songs, only: [:play] do
                member do
				  get "play"
				  get "full_play"
				  
                end
				 collection do
				 	 get "recent_play_list"
				 	 get "all_songs"
				 	 
				 end
				  post "review"
				  get "reviews"
				  get "remove_from_favorite"
				  get "add_to_favourite"
            end
		end
	end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController <  Admin::ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  layout 'admin'
  helper_method :sort_column, :sort_direction
  # GET /admin/users
  # GET /admin/users.json
  before_action :save_my_previous_url

    def save_my_previous_url
    # session[:previous_url] is a Rails built-in variable to save last url.
     session[:my_previous_url] = URI(request.referer || '').path
   end
   def index
    
    if params[:commit] == "Search"
      if params[:artist].present?
      @users = User.where(admin: false).where(role: "A").order("created_at desc").search(params[:user][:text]).paginate(:page => params[:page])
       
       
      else
      @users = User.where(admin: false).where(role: "U").order("created_at desc").search(params[:user][:text]).paginate(:page => params[:page])
    
      end
      
    else
      if params[:direction].present?
         if params[:artist].present?
        @users = User.order(params[:sort] + ' ' + params[:direction]).where(admin: false).where(role: "A").paginate(:page => params[:page])
        else
           @users = User.order(params[:sort] + ' ' + params[:direction]).where(admin: false).where(role: "U").paginate(:page => params[:page])
      end
      else
         if params[:artist].present?
        @users = User.where(admin: false).where(role: "A").order("created_at desc").paginate(:page => params[:page])
        else
           @users = User.where(admin: false).where(role: "U").order("created_at desc").paginate(:page => params[:page])
           end
      end
    end
  end
    def check_email
     
        user =      User.find(params[:user_id])
        check = User.where.not(id:  user.id).find_by_email(params[:user][:email])
        # if(user.email!=params[:user][:email])
        #   @user = User.find_by_email(params[:user][:email])
        #   end
          
          hsh={}
          if check.present?
            hsh=false
          else
            hsh=true
          end
          render :json => hsh
        # if current_user.present?
        #   if(current_user.email!=params[:user][:email])
        #   @user = User.find_by_email(params[:user][:email])
        #   end
        #   else
        #   @user = User.find_by_email(params[:user][:email])
        # end
        

      end
    def sort_direction
      %w[asc desc].include?(params[:direction]) ?  params[:direction] : "asc"
  end

  def sort_column
      User.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end
def dashboard
end
  # GET /admin/users/1
  # GET /admin/users/1.json
  def show
  end

  # GET /admin/users/new
  def new
    @user = User.new
  end

  # GET /admin/users/1/edit
  def edit
  end

  # POST /admin/users
  # POST /admin/users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to [:admin, @user], notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  def status
    user = User.find(params[:user_id])
    user.update_attributes(status: !(user.status))
    redirect_to  admin_users_path
  end
  # PATCH/PUT /admin/users/1
  # PATCH/PUT /admin/users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to [:admin, @user], notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  def change_password
  # debugger
  end
  def update_password
        

  if current_user.valid_password?(user_params[:current_password])     
      current_user.update(:password=>user_params[:password])
    
    else
      flash[:error] = "Please enter correct current password!"
      redirect_to   admin_change_password_path
    end
  end
   def sort_direction
      %w[asc desc].include?(params[:direction]) ?  params[:direction] : "asc"
  end

  def sort_column
      User.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end
  # DELETE /admin/users/1
  # DELETE /admin/users/1.json
  def destroy
    puts "in destroy"
  @user.destroy

    puts "after destroy"
    respond_to do |format|
    puts "in format"
      format.html { redirect_to admin_users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :image, :email, :city, :state, :mobile, :status,:admin,:role)
    end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
def create
  
  resource = User.find_for_database_authentication(email: params[:user][:email])
  
  return invalid_login_attempt unless resource

  if resource.valid_password?(params[:user][:password])
    sign_in :user, resource
    return render nothing: true
  end

  invalid_login_attempt
 end
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected
  def invalid_login_attempt
  set_flash_message(:alert, :invalid)
  render json: flash[:alert], status: 401
end
  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	  before_action :authenticate_user!
	 before_action :check_login
	 before_action :save_my_previous_url
	 before_action :check_user_privilige

    def save_my_previous_url
    # session[:previous_url] is a Rails built-in variable to save last url.
     session[:my_previous_url] = URI(request.referer || '').path
   end

	 def my_profile
	 	

	 	@profile_like =   current_user.favourites.count
	 	@song_like =   Favourite.where(:favourable_id=>current_user.songs,:favourable_type=>'Song').count
	    @song_view =   RecentlyPlay.where(:song_id=>current_user.songs).count
	    @facebook = current_user.user_social_links.find_by(url_type: "facebook")
	  @instagram = current_user.user_social_links.find_by(url_type: "instagram")
	  @twitter = current_user.user_social_links.find_by(url_type: "twitter")
	 end
	 def profile
	 	@genere = Genre.all
	 	return_hash = HashWithIndifferentAccess.new
	 	return_hash[:message]= current_user.first_name+" "+current_user.last_name+" new artist has been register on tune reward stay tune to listen new  songs"
	    @alluser = SubscribeNews.all
	    @alluser.each do |user|
	    
           return_hash[:email]= user.email
           # UserMailer.news_letter_mailer(return_hash).deliver_now;
           UserMailer.delay(run_at: 5.seconds.from_now).news_letter_mailer(return_hash)
         
      end
	 end
	  def usersetting
		 
	  @facebook = current_user.user_social_links.find_by(url_type: "facebook")
	  @instagram = current_user.user_social_links.find_by(url_type: "instagram")
	  @twitter = current_user.user_social_links.find_by(url_type: "twitter")
	   @itune = current_user.user_social_links.find_by(url_type: "itune")
	  @spotify = current_user.user_social_links.find_by(url_type: "spotify")
	  @soundcloud = current_user.user_social_links.find_by(url_type: "soundcloud")
	 end
	 
   def update_profile
   	 params[:user][:dob] = params[:user][:dob].to_date
     params[:user][:dob] = params[:user][:dob].strftime('%Y-%m-%d')
     current_user.update(:age=>params[:user][:age],:dob=>params[:user][:dob],:first_name=>params[:user][:first_name],:last_name=>params[:user][:last_name],:image=>params[:user][:image],:username=>params[:user][:username])
	 current_user.build_user_genre(genre_id:params[:genre_id]).save
      if params[:url].present?
         params[:url].each do |key, value|
     	if current_user.user_social_links.find_by(url_type: key).present?
     	current_user.user_social_links.where(url_type:key).update(url:value)
     	else
	   current_user.user_social_links.create(url_type:key,url:value)
	  end	
	end
 end
	redirect_to my_profile_path
	end
   def update_password
	
	if current_user.valid_password?(params[:user][:current_password])			
      current_user.update(:password=>params[:user][:password])
	  redirect_to  new_user_session_path
    else
    	flash[:danger] = "Current password is not correct.Please enter correct current password!"
    	redirect_to    usersetting_path
    end
	end
	 def check_user_privilige
      if current_user
       if current_user.admin
        redirect_to  admin_path
      end
    end
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<div class="col-lg-10" style="width: 78%;">
<%= form_for([:admin, @user],html: {class: "form-horizontal edit_user"}) do |f| %>

  <div class="form-group">

      <%= f.label :first_name,class: "control-label col-sm-2" %>
      <div class="col-md-10">
    <%= f.text_field :first_name,class: "form-control",style: "max-width: 500px;",required: true, maxlength: "50" %>
    </div>
    </div>
       <div class="form-group">
        <%= f.label :last_name,class: "control-label col-sm-2" %>
           <div class="col-md-10">
        <%= f.text_field :last_name, :class => 'form-control', :placeholder=>"Last Name",:required => true, maxlength: 25,minlength: 3,:pattern=>"^[a-zA-Z \.\,\\-]*$",style: "max-width: 500px;"  %>
        </div>
        </div>
          <% unless params[:admin]  %>
         

        <div class="form-group">
        <%= f.label :email,class: "control-label col-sm-2" %>
           <div class="col-md-10">
        <%= f.text_field :email, :class => 'form-control', :id=> "email", :placeholder=>"Email",:required => true,style: "max-width: 500px;" %>
        </div>
         </div>
           
       
      <% if params[:artist] %>
        <div class="form-group">
         <%= f.label :dob,class: "control-label col-sm-2" %>
            <div class="col-md-10">
        <%= f.text_field :dob, :class => 'form-control date', :id=> "dob", :placeholder=>"Date Of Birth",:required => true,style: "max-width: 500px;" %>
        </div>
         
        </div>
        <% else %>
        <div class="form-group">
         <%= f.label :city,class: "control-label col-sm-2" %>
            <div class="col-md-10">
        <%= f.text_field :city, :class => 'form-control', :id=> "city", :placeholder=>"City",:required => true,style: "max-width: 500px;" %>
        </div>
         
        </div>
          <div class="form-group">
         <%= f.label :state,class: "control-label col-sm-2" %>
            <div class="col-md-10">
        <%= f.text_field :state, :class => 'form-control', :id=> "state", :placeholder=>"State",:required => true,style: "max-width: 500px;" %>
        </div>
         
        </div>
     
           <div class="form-group">
            <%= f.label :mobile,class: "control-label col-sm-2" %>
               <div class="col-md-10">
           <%= f.telephone_field :mobile, :class => 'form-control', :placeholder=>"Mobile Number",:required => true,:pattern=>"^(\\d|\\s)+$" ,maxlength: 11,minlength: 3,style: "max-width: 500px;" %>
           </div>
             
              </div>
                 <% end %>
         <% end %>
  <div class="form-group">
    <%= f.label :image,class: "control-label col-sm-2" %>
    <div class="col-md-10">
  <%= f.file_field :image,class: "file",value: @user.image, accept: "image/*"%>
  </div>
</div>
<% if(@user.present?) %>
<div class="form-group" style="padding-left: 16%;">
       <%if @user.image.present?%>
        <img id="blah" src="<%=@user.image%>" class= "form-control img-thumbnail" />
       
        <%end%>
     </div>
     <% end %>
      
  <div class="actions" style="padding-left: 16%;">
  <% if(@user) %>
    <%= f.submit "Update Now" ,class: "btn btn-success" %>
    <%= link_to 'View', [:admin, @user], class: "btn btn-info",style: "margin-top: 16px;" %>
      <%= link_to 'Back', admin_users_path, class: "btn btn-info",style: "margin-top: 16px;" %>
      <% else %>
       <%= f.submit "Submit" ,class: "btn btn-success" %>
      <% end %>
  </div>
<% end %>
<input type="hidden" id="user_id" value="<%= @user.id %>">
</div>
<style type="text/css">
  .img-thumbnail {
    padding: 0px;
    line-height: 1.428571429;
    background-color: #ededed;
    border: 0px solid #ddd;
    border-radius: 4px;
    max-width: 66px;
    height: 66px;
    margin-left: 14px;
  }
  .datepicker {
  margin-top: 55px;
}
</style>
<script async defer type="text/javascript" src="http://maps.googleapis.com/maps/api/js?key=AIzaSyAWgTptnMkFX0qGYvrOlGux2Af_erw18zs&&libraries=places"></script>
<script type="text/javascript">
 
  $(document).ready(function(){

   
   var user_id = $("#user_id").val();
    $(".file").change(function(event){
       var input = $(event.currentTarget);
       var file = input[0].files[0];
       var reader = new FileReader();
       reader.onload = function(e){
           image_base64 = e.target.result;
           preview.attr("src", image_base64);
       };
       reader.readAsDataURL(file);
    });

 $('#dob').datepicker({
           autoclose: true,
            format: 'mm/dd/yyyy',
            endDate: '30/12/2006',
           
        });
       
      jQuery.validator.addMethod("matches", function(phone_number, element) {
         phone_number = phone_number.replace(/\s+/g, "");
          return this.optional(element) || phone_number.length > 9 && 
          phone_number.match(/^\d*[0-9](|.\d*[0-9]|,\d*[0-9])?$/);
      }, "<br />Please specify a valid phone number");
$(".edit_user").validate({

rules: {
"user[first_name]": {required: true,minlength: 3,maxlength: 25},
"user[last_name]": {required: true,minlength: 3,maxlength: 25},
"user[email]": {required: true, email: true,remote:"/admin/check_email?user_id="+user_id},

"user[city]": {required: true},

"user[mobile]": {matches: true},


},
messages:{
   "user[first_name]": {
                    pattern: "Please specify a valid first name"
                },
 "user[last_name]": {
                    pattern: "Please specify a valid last name"
                },
  "user[email]": {
                    remote: "Email already exist"
                },
   
  
  "user[mobile]": {
                    pattern: "Please specify a valid phone number"
                },

  "user[city]": {
                    pattern: "Please specify a valid city name"
                },
 "user[image]": {
                    accept: "Please select png or jpg file"
                },
                
  
}
});


});


  
</script>

app/views/admin/users/dashboard.html.erb
 <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-0 main">

          <h1 class="page-header text-muted">DASHBOARD</h1>
<!-- Widgets -->
            <div class="row clearfix">
            <a role="button" href="admin/users">
                <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                    <div class="info-box bg-pink hover-expand-effect">
                        <div class="icon">
                    <i class="fa fa-fw fa-user"></i>
                        </div>
                        <div class="content">
                            <div class="text">User<h4><%= User.where(:role=>"U").where(:admin=>false).count %></h4></a></div>
                            <div class="number count-to" data-from="0" data-to="125" data-speed="15" data-fresh-interval="20"></div>
                        </div>
                    </div>
                </div>
              
                <a role="button" href="admin/users?artist=true">
                <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                    <div class="info-box bg-indigo hover-expand-effect">
                        <div class="icon">
                              <i class="fa fa-fw fa-user"></i>
                        </div>
                        <div class="content">
                            <div class="text">Artist<h4><%= User.where(:role=>"A").count %></h4></div>
                            <div class="number count-to" data-from="0" data-to="125" data-speed="15" data-fresh-interval="20"></div>
                        </div>
                    </div>
                </div>
                </a>
               
                
            </div>



<style type="text/css">
  .col-md-offset-0 {
    margin-left: 0%;
}
.col-md-10 {
    width: 100%;
}
.highcharts-background{
 box-shadow: "-1px 4px 10px 10px #888888;" 
}
h4{
padding-left: 20px;
}
.col-lg-3 {
    width: 25%;
}
</style>
<%  max = User.count + User.count + User.count %>






</div>

<style type="text/css">
    #wrapper {
    margin-top: -30px;   
}
.col-lg-4 {
    width: 24.333%;
}
</style>
<script type="text/javascript">
     window.onpopstate = function() {
    }; history.pushState({}, '');
</script>

app/views/admin/users/edit.html.erb
<div class="page-header">
<% if @user.role=="U" %>
  <h1>Editing User</h1>
  <%else%>
   <h1>Editing Artist</h1>
  <%end%>
</div>

<%= render 'form' %>

<%#= link_to 'Show', [:admin, @user], class: 'btn btn-default' %>
<%#= link_to 'Back', admin_users_path, class: 'btn btn-default' %>

app/views/admin/users/index.html.erb
<div class="row unit_list">
   <div class="col-sm-8 col-md-8">

<h1 class="text-muted">LISTING USERS</h1>
 
<div class="radio_top">
         <div class="custom_radio">
            <input type="radio" id="user" name="radio-group" checked>
             <label for="user">User</label>
         </div>
         <div class="custom_radio">
            <% if params[:artist].present? %>
             <input type="radio" id="artist" name="radio-group" checked>
             <% else %>
              <input type="radio" id="artist" name="radio-group" >
             <% end %>
             <label for="artist">Artist</label>
         </div>
      </div>
</div>

<div class="col-sm-4 col-md-4 align-right">

<div class="field">

   <%= form_for(:user,url: admin_users_path ,method: :get) do |f| %>
    <% if params[:artist].present? %>
   <%= hidden_field_tag :artist, true%>
   <%end%>
   <%= f.text_field :text,placeholder: "Search by name/email",style:"width: 173px;",:required=>true, id: "search",:value=> "#{ params[:user] ? params[:user][:text] : ''}"%>

   <%= f.submit "Search",class: "btn btn-primary"%>
   <% end %>
</div>
</div>
</div>
<table class="table table-responsive table-hover table-bordered  table-condensed">
  <thead>
    <tr>
       <th><%= sortable "first_name" %> <i class="fa fa-sort"></i></th>
           <th><%= sortable "last_name" %> <i class="fa fa-sort"></i></th>
         <th><%= sortable "email" %> <i class="fa fa-sort"></i></th>
      <th>Image</th>
       <% unless params[:artist].present? %>
      <th>City</th>
      <th>State</th>
      <th>Mobile</th>
     <% end %>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
         <td><%= user.email %></td>
        <td>
       <%if user.image.present?%>
       <%=image_tag user.image ,alt: '',size: "46x46",style: "margin-top: 7px;"%>
         <%else%>
          <%=image_tag "default_user.png",alt: '',size: "46x46",style: "margin-top: 7px;"%>

         <%end%>
       </td>
          <% unless params[:artist].present? %>
        <td><%= user.city %></td>
        <td><%= user.state %></td>
        <td><%= user.mobile %></td>
       <% end %>
        <td><%= link_to 'View', [:admin, user], class: 'btn btn-default btn-xs' %></td>
        <td> <% if(user.role=='A') %>
              <%= link_to "Edit", edit_admin_user_path(user.id)+"?artist=true",title: 'Edit', class: 'btn btn-default btn-xs',:style=>"color:#337ab7"%>
              <% else %>
                <%= link_to "Edit",  edit_admin_user_path(user.id),title: 'Edit', class: 'btn btn-default btn-xs',:style=>"color:#337ab7"   %> 
              <% end %>
      </td>
        <td><%= link_to 'Destroy', [:admin, user], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-xs btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%#= link_to 'New User', new_admin_user_path, class: 'btn btn-primary' %>
<% if @users.blank?%>
<i><span style="font-size: 25px; margin-left: 38%;">No User Found</span></i>
<%end%>
<div class="digg_pagination">
   
    <%= will_paginate @users, :container => false %>
  </div>

<script>
$(document).ready(function(){
   $('#user').click(function(){
      window.location.href ='/admin/users';
   });
   $('#artist').click(function(){
      window.location.href = '/admin/users?artist=true';
   });
});
</script>

app/views/admin/users/new.html.erb
<div class="page-header">
  <h1>New user</h1>
</div>

<%= render 'form' %>

<%= link_to 'Back', admin_users_path, class: 'btn btn-default' %>

app/views/admin/users/show.html.erb
<% if User.find_by_id(params[:id]).admin.present? %>

<%= link_to 'Back', "/admin/users/#{params[:id]}/edit?admin=true",class: "btn btn-info"%>

<% else %>
<% if @user.role == "A" %>
<%= link_to 'Back', "/admin/users?artist=true" ,class: "btn btn-info"%>

<%else%>
<%= link_to 'Back', admin_users_path(page: params[:page]) ,class: "btn btn-info"%>

<%end%>
<% end %>
<div class="well">
   <div class="row">
      <div class="col-sm-4 col-md-2">
         <%if @user.image.present?%>
         <%=image_tag @user.image ,alt: '',class: "img-rounded img-responsive",:size => "380x500" %>
         <%else%>
         <%= image_tag "default_user.png",class: "img-img-rounded img-responsive",:size => "380x500"%>
         <%end%>
      </div>
      <div class="col-sm-8 col-md-10">
         <% if @user.first_name.present? %>
        <span><h4>Name:</h4><%=@user.first_name%> <%=@user.last_name%></span>
         <%end%>
         <br/>
       
          <% if @user.city.present? %>
          <span><h4>City:</h4><%=@user.city%> </span>
          <%end%>
       
        <span><h4>Email:</h4><%=@user.email%> </span>
         <% if @user.mobile.present? %>
         <span><h4>Mobile:</h4><%=@user.mobile%> </span>  
             <%end%>
      </div>
   </div>
</div>
</div>
<style type="text/css">
   .glyphicon {  margin-bottom: 10px;margin-right: 10px;}
   small {
   display: block;
   line-height: 1.428571429;
   color: #999;
   }
   .back{
   margin-top: 12px;
   }
</style>