config/routes.rb
Rails.application.routes.draw do




  namespace :admin do
    resources :point_infos
  end
  namespace :admin do
  resources :user_gift_requests do
     member do
     get "gift_request_send"
     end
  end
  end
  namespace :admin do
    resources :offers
  end
	root "common#index"


# resources :albums do
# 	member do
# 		get 'album_songs'
# 	end
# end
    resources :subscribe_news do
    collection do
    	post 'subscribe_me' => "subscribe_news#subscribe_me"
    end
   end
    resources :notifications do
    	collection do
         get 'unread_notification' => "notifications#unread_notification"
         get 'notification_list' => "notifications#notification_list"
         post 'update_notification' => "notifications#update_notification"

       end
   end
	resources :albums do
     member do
      	get 'album_songs' => "albums#republic"
      end
      collection do
	   get 'add_album' => "albums#add_album"
	   post 'create_album' => "albums#create"
	   get 'albums' => "albums#index"
	   

     end
   end
   resources :genres , except: [:show]  do
   	collection do
   	get 'upload_song' => "genres#upload_song"
   end
   end
    resources :songs 
     post 'add_song'=>"songs#create"

    resources :user
	get 'profile' => "users#profile"
	put "update_password" => "users#update_password"
    
	get 'usersetting' => "users#usersetting"
	get 'my_profile' => "users#my_profile"
	patch 'update_profile' => "users#update_profile"
	get 'notifications' => "notifications#notifications"
	get 'setting' => "notifications#setting"
  
	get 'forgetpassword' => "common#forgetpassword"
     post "social_login" => "common#social_login"
	get 'contact_us' => "common#contact_us"
	get 'about_us' => "common#about_us"
	get 'privacy' => "common#privacy"
	get 'how_it_work' => "common#how_it_work"
	

	get  "common/check_email"
 



  namespace :admin do
    resources :genres
  end
  namespace :admin do
    resources :users
    
    get "/" => "users#dashboard"
    
    get "/change_password" => "users#change_password"
    get "/update_password" => "users#update_password"
    get  "/check_email"   => "users#check_email"
 
    
  end

   get "set_password" => "common#set_password"
   put "updatepassword" => "common#update_password"
   
  
# devise_for :users, controllers: {
#   sessions: 'users/sessions'
# }

   devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

	namespace :api, defaults: { format: :json } do
		namespace :v1 do
			resources :users, only: [:index] do
				collection do
				  get "me"
				  post "sign_in"
				  get "sign_out"
				  post "sign_up"
				  post "update"
				  get "recent_music"
				  get "followings"
				  get "followers"
				  post "review"
				  get "reviews"
				  post "select_genre"
				  get "common_genre"
				  post "forgot_password"
				  post "varify_otp" 
				  post "varify_forgot_otp" 
				  post "update_password" 
				  post "change_current_password" 
				  get "get_points"
				  get "get_offers"
				   post "resend_otp"
				   post "browse"
				   post "social_login"
				   post "setting_notification"
				   get "all_notification"
				   get "unread_notification"
				   
				end
				member do
				  get "profile"
				  get "add_new_point"
                 end
				  get "follow"
				  get "unfollow"
				  get "remove_from_favorite"
				  get "add_to_favourite"
			end
			resources :user_playlists do
				get "playlist_songs"
				post "add_song"
				get  "delete"

			end
			 resources :offers do
			    	 member do
			      	get 'redeem_offer' => "offer#redeem_offer"
			      end
              end
			resources :genres, only: [:index] do
				resources :albums, only:[:index,:show]
				collection do
				  get "all"
				 end
			end
			 
			
			
            resources :songs, only: [:play] do
                member do
				  get "play"
				  get "full_play"
				  
                end
				 collection do
				 	 get "recent_play_list"
				 	 get "all_songs"
				 	 
				 end
				  post "review"
				  get "reviews"
				  get "remove_from_favorite"
				  get "add_to_favourite"
            end
		end
	end

end

app/controllers/api/v1/common_controller.rb
class Api::V1::GenreController < Api::V1::ApplicationController
	def all
			
			begin
				     @genre = Genre.all
					 render :show_genre
				
		 	rescue Exception => e
		 		puts "error_exception #{Time.now} #{e.message}"
				err_hash={}
				err_hash[:error]=e.message
				render :json => err_hash.to_json  , status: :bad_request 
		 	end
		end

        def album
			
			begin
				 album_ids =Album.joins(:songs).where('songs.is_submit'=>1).where("albums.genre_id"=>params[:genre_id]).map(&:id).uniq
				     @album = Album.where(:genre_id=>params[:genre_id]).where(:id=>album_ids)
					 render :show_album
				
		 	rescue Exception => e
		 		puts "error_exception #{Time.now} #{e.message}"
				err_hash={}
				err_hash[:error]=e.message
				render :json => err_hash.to_json  , status: :bad_request 
		 	end
		end

       
end

app/controllers/common_controller.rb
class CommonController < ApplicationController
  skip_before_action :verify_authenticity_token
  
    before_action :check_user_privilige
	def index
    # @users = User.where(:role=>"A").where(:id => Favourite.where(:favourable_type => "User").group(:favourable_id).order('count_id DESC').count(:id).keys )
    # @users = User.where(:id => Favourite.where(:favourable_type => "User").group(:user_id).order('count_id DESC').count(:id).keys ).limit(10)
    # @users = User.where(:id => Favourite.where(:favourable_type => "User").group(:user_id).order('count_id DESC').count(:id).keys ).limit(10)
    @users = Favourite.popular
	end
      
   def check_email
       	# if(current_user.email!=params[:user][:email])
        #   @user = User.find_by_email(params[:user][:email])
         
        #  	else
          @user = User.find_by_email(params[:user][:email])
        # end
      hsh={}
    if  @user.present?
            hsh=false
          else
            hsh=true
          end
          render :json => hsh
    # respond_to do |format|
    # format.json { render :json => !@user }
    #  end
    end
     def check_user_privilige
   
   
   
    if current_user
      if current_user.admin
        redirect_to  admin_path
      end
    end
  end
    def social_login

      begin
        
      login_with_facebook(params) 
      @user.update_attributes!(role: "A")
      current_user = @user
      # raise "This account has been suspended by admin" if @user.suspend
       sign_in(@user, scope: :user)
        if(@user.age==nil)
        render :js => "window.location.href = '/profile'"
      else
        render :js => "window.location.href = '/my_profile'"
      end
         # redirect_to profile_path
      rescue Exception => e
        puts e.message
        err_hash={}
        err_hash[:error]=e.message
        render :json => err_hash.to_json, status: :bad_request 
      end
      
    end
        def login_with_facebook(params)
        
      fb_info = User.connect_with_facebook(params[:access_token])
    
      raise "Access token is invalid." if fb_info[:error].present?
        email = fb_info[:email].nil? ? "#{fb_info[:id]}@facebook.com" : fb_info[:email]
        if User.find_by(email: fb_info[:email]).present?
          @user = User.find_by(email: fb_info[:email])
          # raise "Your email is not verified,please verify before login." unless @user.is_email_verified.try(:to_bool)
          # raise "Please wait till your account is verified by admin." if @user.approve.blank? && @user.profile_completed.present?
        elsif User.find_by(social_id: fb_info[:id]).present?
          @user = User.find_by(social_id: fb_info[:id])
          # raise "Your email is not verified,please verify before login." unless @user.is_email_verified.try(:to_bool)
          # raise "Please wait till your account is verified by admin." if @user.approve.blank? && @user.profile_completed.present?
        elsif fb_info[:error].blank?
          fb_id = fb_info[:id]
          first_name = fb_info[:first_name].nil? ? "" : fb_info[:first_name]
          last_name = fb_info[:last_name].nil? ? "" : fb_info[:last_name]
          full_name = first_name + " " + last_name
          password = Devise.friendly_token
          verified_status =  fb_info[:email].present? ? true : false
          @user = User.new(:first_name=>first_name,:last_name=>last_name,:social_id=>fb_id,:email=>email,:password=>password,role: "A")
          image_url = "https://graph.facebook.com/#{fb_info[:id]}/picture?type=large"
          avatar_url =image_url.gsub("­http","htt­ps")
          avatar_url_new = process_uri(avatar_url)
          @user.image = avatar_url
          @user.save

        else
        raise "access token is invalid"
      end

      # @user.update_attributes!(:current_time_zone => params[:user][:current_time_zone]) if params[:user][:current_time_zone].present?   
    end
    def set_password
       @user = User.find_by_fp_token(params[:token])
       
    end
def update_password
  @user = User.find_by_fp_token(params[:user][:fp_token])
   if @user.present?  
      
      @user.update(:password=>params[:user][:confirm_password],:fp_token=>"")
      flash[:success] = "Password Changed successfully!"
      redirect_to  root_path
    else
      flash[:danger] = "Forget password link expired!"
      redirect_to    root_path
    end
  end

end

app/helpers/common_helper.rb
module CommonHelper
end

app/views/common/about_us.html.erb
<div class="main_content">
        <!-- find -->
        <section class="top_heading text-center">
        <div class="container">
        <h3>About Us</h3>
        </div>
        </section>
        <section class="user_setting">
        <div class="container">
          
        <div class="container-fluid text-center">    
  <div class="row content">
    <div class="col-sm-1 sidenav">
     <!--  <p><a href="#">Link</a></p>
      <p><a href="#">Link</a></p>
      <p><a href="#">Link</a></p> -->
    </div>
    <div class="col-sm-10 text-left"> 
     
      <p>Tune Rewards – Free Money Music is the world’s first and only IOS music and audio streaming platform that pays users to listen to music uploaded by artists.</p><br>
      <p>We are currently in our beta phase and are looking for artists of all genres to upload their music! </p><br>
      <p>Here at Tune Rewards we take a different approach to streaming. Instead of trying to have the largest music catalog like Apple Music or Spotify, we realized that developing artists benefit most from high visibility and low competition. This is why Tune Rewards decided to limit the number of songs allowed in each genre to just 1000 and every 2 weeks, the songs are taken off the app and replaced with another 1000 songs uploaded by artists. What this does is increase traffic and visibility to artists on the app while also giving new artists the chance to be seen.</p><br>
      <p>To encourage people to discover the music, Tune Rewards converts plays and listens into points which can be spent within the apps marketplace on goods, services, and cash prizes. </p>
    </div>
    <div class="col-sm-9 sidenav">
     
    </div>
  </div>
</div>
          </div>

          </section>

app/views/common/contact_us.html.erb
<div class="main_content">
        <!-- find -->
        <section class="top_heading text-center">
        <div class="container">
        <h3>Contact Us</h3>
        </div>
        </section>
        <section class="user_setting">
        <div class="container">
          
        <div class="container-fluid text-center">    
  <div class="row content">
    <div class="col-sm-1 sidenav">
     <!--  <p><a href="#">Link</a></p>
      <p><a href="#">Link</a></p>
      <p><a href="#">Link</a></p> -->
    </div>
    <div class="col-sm-10 text-left"> 
     
      <p class="text-center">If you want to sell your products on TuneRewards and get our users to see them featured on our offers page:</p><br>
      <p class="text-center"><b>partner@tunerewardsapp.com</b></p><br>

      <p class="text-center">For any other info:</p><br>
      <p  class="text-center"><b>info@tunerewardsapp.com</b></p><br>
    </div>
    <div class="col-sm-9 sidenav">
     
    </div>
  </div>
</div>
          </div>

          </section>

app/views/common/forgetpassword.html.erb
 <div class="main_content">
      <!-- find -->
      <section class="top_heading text-center">
         <div class="container">
            <h3>forgot your password?</h3>
         </div>
      </section>
      <!-- start form area here -->            
      <section class="fotget">
         <div class="container">
            <div class="forget_new">
               <%= image_tag ("email.png") %>
               <div class="text-center retrive">
                  <p>Enter your email address to retrive</p>
                  <p>your password?</p>
               </div>
               <form class="edit_pro">
                  <%= form_for(:user, :html => {:class => "edit_pro", :role => "form" }, url: @forgetpassword2_path) do |f| %>
                  <div class="form-group">
                     <%= f.label :Email_address, :style => "color: #fff;", :for => "exampleInputEmail1" %>
                     <%= f.email_field :email, :class => "form-control", :id => "exampleInputEmail1", :placeholder => "Enter your email address" %>
                  </div>
                  <%= link_to 'Submit', @root_path, :class => "btn sign", :role => "button" %>
               <% end %>
            </div>
         </div>
      </section>
      <!----popup sign in----->
      <div class="modal fade" id="squarespaceModal3" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
         <div class="modal-dialog form_top">
            <div class="modal-content">
               <div class="modal-header close_head">
                  <button type="button" class="close custome" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
               </div>
               <div class="modal-body">
                  <!-- content goes here --> 

        <%= render "/layouts/popup" %>
    
    <script src="js/jquery.js" type="text/javascript"></script>
      <script src="js/bootstrap.js" type="text/javascript"></script>
      <script src="js/owl.carousel.min.js"></script>
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.2/css/bootstrap-select.min.css">
      <!-- Latest compiled and minified JavaScript -->
      <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.2/js/bootstrap-select.min.js"></script>
     
     <script>
         $("#face_book_signup").click(function(){
       $('#squarespaceModal3').hide();
       $('#squarespaceModal4').show();
       $('#squarespaceModal4').modal('show');
         });
          $(".loginPopup").click(function(){
       $('#squarespaceModal4').hide();
       $('#squarespaceModal3').show();
       $('#squarespaceModal3').modal('show');
         });
      </script>
   </body>
</html>
               

app/views/common/how_it_work.html.erb
<div class="main_content">
        <!-- find -->
        <section class="top_heading text-center">
        <div class="container">
        <h3>How it works</h3>
        </div>
        </section>
        <section class="user_setting">
        <div class="container">
          
        <div class="container-fluid text-center">    
  <div class="row content">
    <div class="col-sm-1 sidenav">
     <!--  <p><a href="#">Link</a></p>
      <p><a href="#">Link</a></p>
      <p><a href="#">Link</a></p> -->
    </div>
    <div class="col-sm-10 text-left"> 
     <h2>Listeners:</h2>

   <ul style="list-style-type:square">
        <li>Tune Rewards gives you the oppurtunity to earn up to $5 per day for discovering and reviewing new music. </li>
        <li>Users earn points for listening to and reviewing songs, these points can then be redemmed for amazon giftcards and in the future can be redeemed for good, services, and experiences</li>
        <li>Every two weeks you can enjoy a new catalog of tunes which will replace the previous music on the app – Found an artists you love but there music is about to be replaced? No worries. All artists are able to directly link their social media and other streaming accounts directly into their artists profile so you can join their journey as their popularity rises. </li>
        <li>Connect with your friends and compete to see who can earn the most</li>
  </ul>  
    <h2>Artists:</h2>

   <ul style="list-style-type:square">
        <li>Upload your music and get the recognition you deserve. With a limit on the amount of music allowed before a new catalog is released,  Tune Rewards is the best streaming platform guaranteed to boost your exposure and get you more fans and listeners.</li>
        <li>Market yourself: With Tune Rewards, you can connect your Instagram, Twitter and Facebook accounts directly onto the app so fans can find you more easily</li>
        <li>Promote your music: You can also connect your Spotify, Apple Music, and Soundcloud profiles directly onto your account </li>
        <li>The best part? It’s all FREE</li>
  </ul> 
    </div>
    <div class="col-sm-9 sidenav">
     
    </div>
  </div>
</div>
          </div>

          </section>

app/views/common/index.html.erb
      <!-- main_content -->
      <div class="main_content">
      <!-- find -->
      <section class="banner">
         <div class="container">
            <div class="text-center banner-text">
               <h1>Create Your Profile</h1>
               <h2>Upload your music </h2>
               <p>Watch your fanbase grow </p>
               <%= image_tag ("wave.png") %>
            </div>
         </div>
      </section>
      <!-- start artists area here -->		        
      <section class="artists">
         <div class="container">
            <h1>Popular Artists</h1>
           
            <%# @albums.each do |a| %>
            <% if @users.present? %>
             <div class="owl-carousel owl-theme">
            <% @users.each do |u| %>
               <div class="item">
                 <% if u.image.present? %>
                     <%= image_tag u.image,alt: 'Artist Image', :id => "profile_image" %>
                     <% else %>
                     <%= image_tag ("default_user.png"), :id => "profile_image", :alt => "Profile Image" %>
                     <% end %>
                  <%#= image_tag (u.image) %>

                  <h4><%= u.username %></h4>
               </div>
               <%end%>
                </div>
                   <%else%>
                     <h3 style="color:#808080;text-align: center;">No popular artist found </h3>   
                   <%end%>
            
           
         </div>
      </section>
      <!-- end Chefs area here -->
      <!-- start Our Newsletter area here -->
       <section class="analytics">
         <div class="container">
            <div class="row">
               <div class="col-sm-6 analytics_text">
                   <h1>View Your Analytics</h1>
                  <p>You can easily see where the majority of your listeners are located. View day by day performance of your music. See real time reviews of your music by listeners.
                  </p>
                  <%= link_to 'Get Started', "#", class: "btn register loginPopup", :role => "button" %>
               </div>
               <div class="col-sm-6 laptop">
                  <%= image_tag ("laptop.png") %>
               </div>
            </div>
         </div>
      </section>
      <!-- end Our play area here -->	
      <section class="play">
         <div class="container">
            <div class="row">
               <div class="col-sm-6 play_img">
                <%= image_tag ("man.png") %>
               </div>
               <div class="col-sm-6 play_text">
                  <h1><span style="color:#3d428c">Press. <span style="color: #f73974;">Play.</span> <span style="color:#3d428c">Get Paid</span></h1>
                  <p>TuneRewards prides itself on being the first and only IOS app that pays you to discover new music. We track and verify how many songs you’ve listened to and how many reviews you’ve given. Those listens and reviews get converted into points which can then be redeemed for cash prizes.
                  </p>
                   <%#= link_to image_tag('googleplay.png'), '#', class: 'google_play', rel: 'tooltip', relative: true %>
                   <%= link_to image_tag('iphone.png'), '#', class: 'google_play', rel: 'tooltip', relative: true %>
               </div>
            </div>
      </section>
      <section class="newsletter">
      <div class="container">
      <div class="text-center">
      <h1>Stay Tuned For Updates</h1>
      <p>Subscribe to our newsletter for updates, new prize releases and  </br>
      more content from awesome artists.
      </p>
      <%= form_for(:subscribe_news , :html => {:role => "form",:id=>"subscribe_form"}, url:  subscribe_me_subscribe_news_index_path) do |f| %>  
      <div class="form-group email">
      <%= f.email_field :email,email:true, required: true, :pattern => "[^@\s]+@[^@\s]+\.[^@\s]+", :title => "Please specify a valid email address.", class: "form-control", :id => "exampleInputEmail1", :placeholder => "Enter your email address" %>
       
      <span  id="subscribe_now"><i class="fa fa-paper-plane" aria-hidden="true"></i></span>
      </div>
      <% end %>
      </div>
      </div>
      </section>
      </div>
      <!--popup sign in-->
      <div class="modal fade" id="squarespaceModal3" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
         <div class="modal-dialog form_top">
            <div class="modal-content">
               <div class="modal-header close_head">
                    <button type="button" class="close custome" data-dismiss="modal">
                  <span aria-hidden="true" class="close_btn_pop">×</span>
                  <span class="sr-only">Close</span></button>
               </div>
               <div class="modal-body">
                  <!-- content goes here -->

         <%= render "/layouts/popup" %>


    
     <% if @users.count<5 %>
      <script>

      $(document).ready(function(){
        $('.owl-controls').css("display","none");
        
      })
     $("#subscribe_form").validate()
         // $(function(){
         //     $('select').selectpicker();
         // });
         
      </script>
      <% end %>
	  
	  <script>
    $(".custome1").click(function(){

      $('.modal-backdrop').css("display","none");
    
    })
    $("#subscribe_now").click(function(){
     
      if($("#subscribe_form").valid()){
        $("#subscribe_form").submit();
      }else{
         $('.error').css("color","#000");

         }
        })
         $("#face_book_signup").click(function(){
            $('.modal-backdrop').css("display","block");
		 $('#squarespaceModal3').hide();
		 $('#squarespaceModal4').show();
		 $('#squarespaceModal4').modal('show');
         });
      $(".loginPopup").click(function(){
          $('.modal-backdrop').css("display","block");
      $('#squarespaceModal4').hide();
		 $('#squarespaceModal3').show();
		 $('#squarespaceModal3').modal('show');
         });
      </script>
      <script>
         $('.owl-carousel').owlCarousel({
             loop:true,
             margin:30,
             nav:true,
         	navText:['<i class="fa fa-chevron-circle-left" aria-hidden="true"></i>', '<i class="fa fa-chevron-circle-right" aria-hidden="true"></i>'],
             responsive:{
                 0:{
                     items:1
                 },
                 600:{
                     items:2
                 },
                 1000:{
                     items:4
                 }
             }
         })
      </script>

app/views/common/privacy.html.erb
<style type="text/css">
	.wi{
		width:100% !important;
	}
</style>
<div class="main_content">
        <!-- find -->
        <section class="top_heading text-center">
        <div class="container">
        <h3>Privacy Policy</h3>
        </div>
        </section>
        <section class="user_setting">
        <div class="container">
          
        <div class="container-fluid text-center">    
  <div class="row content">
    <div class="col-sm-1 sidenav">
     <!--  <p><a href="#">Link</a></p>
      <p><a href="#">Link</a></p>
      <p><a href="#">Link</a></p> -->
    </div>
    <div class="col-sm-10 text-left wi"> 
     <p>This privacy notice discloses the privacy practices for tunerewardsapp.com . This privacy notice applies solely to information collected by this website. It will notify you of the following:</p>

   <ul style="list-style-type:square">
        <li>What personally identifiable information is collected from you through the website, how it is used and with whom it may be shared.</li>
        <li>What choices are available to you regarding the use of your data.</li>
        <li>The security procedures in place to protect the misuse of your information.</li>
        <li>How you can correct any inaccuracies in the information.</li>
  </ul>  
    <h2>Information Collection, Use, and Sharing </h2>

   <ul style="list-style-type:square">
        <li>We are the sole owners of the information collected on this site. We only have access to/collect information that you voluntarily give us via email or other direct contact from you. We will not sell or rent this information to anyone.</li>
        <li>We will use your information to respond to you, regarding the reason you contacted us. We will not share your information with any third party outside of our organization, other than as necessary to fulfill your request, e.g. to ship an order.</li>
        <li>Unless you ask us not to, we may contact you via email in the future to tell you about specials, new products or services, or changes to this privacy policy.</li>
  </ul> 
    </div>
      <div class="col-sm-10 text-left wi"> 
     <h2>Your Access to and Control Over Information </h2>

     <p>You may opt out of any future contacts from us at any time. You can do the following at any time by contacting us via the email address or phone number given on our website:</p>
   <ul style="list-style-type:square">
        <li>See what data we have about you, if any.</li>
        <li>Change/correct any data we have about you.</li>
        <li>Have us delete any data we have about you.</li>
        <li>Express any concern you have about our use of your data</li>
  </ul>  
    <h2>Security</h2>

   <ul style="list-style-type:square">
        <li>We take precautions to protect your information. When you submit sensitive information via the website, your information is protected both online and offline.</li>
        <li>Wherever we collect sensitive information (such as credit card data), that information is encrypted and transmitted to us in a secure way. You can verify this by looking for a lock icon in the address bar and looking for "https" at the beginning of the address of the Web page.</li>
        <li>In order to use this website, a user must first complete the registration form. During registration a user is required to give certain information (such as name and email address). This information is used to contact you about the products/services on our site in which you have expressed interest.</li>
  </ul> 
    </div>
   <!--  <div class="col-sm-9 sidenav">
     
    </div> -->
    
  </div>
  <br><p>If you feel that we are not abiding by this privacy policy, you should contact us immediately at  or info@tunerewardsapp.</p>
</div>
          </div>

          </section>

app/views/common/privacy_policy.html .erb
<%= image_tag ("come.jpg"), style: 'width:800px; height:600px; text-align:center;' %>

app/views/common/set_password.html.erb
        <div class="main_content">
        <!-- find -->
        <section class="top_heading text-center">
        <div class="container">
        <h3>Reset Password</h3>
        </div>
        </section>
        <section class="user_setting">
        <div class="container">
          
          <div class="row">

        
       
              <div class="password  ">
                <% if @user.present?  %>
                <%= form_for(:user, as: "user", url:    updatepassword_path, :html => { :id => "edit_password", :role => "form",:class=>"edit_pro"},  method: "put",multipart: true ) do |f| %>

             
                <div class="form-group">
                <%= f.label :password, :for => "exampleInputPassword1" %>             
                <%= password_field_tag :password,"",:pattren=>"^(?=.[A-Za-z0-9])[\S]$", maxlength: 32,minlength: 6,class: "form-control",  :id => "password" , :placeholder => "*********"%>
                
                </div>
                 <%= f.hidden_field :fp_token,:value=>params[:token] %>
                <div class="form-group">
                <%= f.label :confirm_password, :for => "exampleInputPassword1" %>             
                <%= f.password_field :confirm_password,  class: "form-control", :id => "confirm_password", :placeholder => "*********" %>
                </div>
                <%= f.submit "Change Password", :class => "btn save change_p" %>

                <% end %>
                <% else %>
                <h3>Your Link has been expired !!! </h3>
                <% end  %>
                  </div>
                     </div>
                      </div>
                     </section>
        </div>


        <script>

        $(document).ready(function () {
           $(document).on('keydown', '#password', function(e) {
           if (e.keyCode == 32) return false;
          });
       
            $(document).on('keydown', '#confirm_password', function(e) {
           if (e.keyCode == 32) return false;
          });
        $("#user_setting").validate();
        setTimeout(function(){ $("#password").val(''); }, 1000);
        
        $(".password form").validate({
        // debug: false,
            rules: {
             
              "user[password]": {required: true, minlength: 6,maxlength:32},
              "user[confirm_password]": {required: true, equalTo: "#password"}
            },
            messages:{
            "user[password]": {
              required: "This field is required"
              },
            "user[confirm_password]": {
              pattern: "This field is required"
              },
            }
        });

});
       

       

        

        </script>